[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\f/home/ludger)
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x93\0\0\0=\0\0\x11l\0\0\x5\x8c\0\0\a\x93\0\0\0=\0\0\x11l\0\0\x5\x8c\0\0\0\x1\0\0\0\0\n\0\0\0\a\x93\0\0\0=\0\0\x11l\0\0\x5\x8c)"

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/ludger/ext_drives/vaults/vault/Media/Videos/yt-dlp/Antonio%20Biaggi%20And%20Papisongo%20%5BxhF53Fa%5D.mp4, file:///home/ludger/vaults/vault/Media/Videos/Porn/Donkey-dick%20Double-fucking%20%5B71824587%5D.mp4, file:///home/ludger/vaults/vault/Media/Videos/yt-dlp/Sexo%20gay%EF%BC%9A%20estacionamento%20de%20jordan%20fox%20%5BxhbfCXe%5D.mp4, file:///home/ludger/vaults/vault/Media/Videos/Porn/Greedy%20liabilities%20and%203%20gifted%20%5B63548877%5D.mp4, file:///home/ludger/vaults/vault/Media/Videos/yt-dlp/3Control%20%5B3662661%5D.mp4, file:///home/ludger/vaults/vault/Media/DJI/Anivers%C3%A1rio%20Vitorelli%202023/DJI_0001.MP4, file:///home/ludger/vaults/vault/Media/DJI/Anivers%C3%A1rio%20Vitorelli%202023/DJI_0012.MP4, file:///home/ludger/vaults/white-vault/Carlos/video-1648640708.mp4, file:///home/ludger/vaults/vault/Media/Videos/Porn/JohnnyRapid%20-%20Hunk%20Threesomes%20Compilation%20FT%20Dalton%20Riley%2C%20Mason%20Lear%20%26%20MORE%21%21%20%5B75811219%5D.mp4, file:///home/ludger/vaults/vault/Media/Videos/Porn/Greg%20and%20Joey%20%20VHS%20Tape%20Video%20%28Official%29%20Full%20%5B2709045%5D.mp4, file:///home/ludger/vaults/vault/Media/Videos/Porn/Gangbang%20four%20guys%20one%20hole%20-%20Brazilians%20%5B50944783%5D.mp4, file:///mnt/vaults/vault/Media/Videos/Porn/Gangbang%20four%20guys%20one%20hole%20-%20Brazilians%20%5B50944783%5D.mp4, file:///home/ludger/vaults/vault/WHITE/JosephCampbell/O%20Poder%20do%20Mito%20e7%20-%20A%20Mitologia%20de%20Star%20Wars%20com%20George%20Lucas.mp4, file:///run/media/ludger/STORAGE/Media/Videos/yt-dlp/NATO%20PER%20INCULARE%20-%20Igor%20%26%20Leon%20%5BxhiMrCO%5D.mp4, file:///run/media/ludger/STORAGE/Media/Videos/yt-dlp/Caipira%20fim%20de%20semana%20%5B12509386%5D.mp4, file:///run/media/ludger/STORAGE/Media/Videos/yt-dlp/Vizinha%20tesuda%20-%20nial%20%5B4645019%5D.mp4
times=-1, -1, -1, 0, -1, -1, -1, 0, 0, 0, 0, 0, 586781, 0, 0, 0
