#################
### AUTOSTART ###
#################

# Wake up the secondary monitor
exec-once = sh -c 'PORT=$(ls /sys/class/drm/card*-HDMI-A-1/status 2>/dev/null | head -n 1); [ -n "$PORT" ] && echo "detect" > "$PORT"'

# Top Bar
exec-once = bash -c "killall waybar; waybar"

# Wallpaper
exec-once = bash -c "killall hyprpaper; hyprpaper & sleep 0.5; ~/.config/hypr/scripts/wallpaper.sh random"

# Hypridle
exec-once = hypridle

# Notifications & Idle Management
exec-once = bash -c "killall swaync; swaync"
exec-once = bash -c "killall hypridle; hypridle"

# Startup Apps
exec-once = $browser

# Scripts
exec-once = systemctl --user start hyprpolkitagent

# Sound effects
exec-once = bash -c "killall easyeffects; easyeffects"