#############
### INPUT ###
#############

input {
    # Keyboard Layout
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =
    
    numlock_by_default = true

    # Mouse / Touchpad
    follow_mouse = 1
    sensitivity = -0.75   # -1.0 - 1.0, 0 means no modification.

    touchpad {
        scroll_factor = 0.6
        natural_scroll = false
    }
}

# Example per-device config for your specific touchpad
device {
    name = synaptics-tm3394-001
    sensitivity = 0.3
}