###################
### MY PROGRAMS ###
###################

# Set programs that you use often
$terminal = kitty 
$fileManager = kitty --class ranger -e ranger
$browser = firefox
$calculator = qalculate-qt
$passwordManager = keepassxc
$sshClient = termius

# Reminder: Using kitty -e ensures the terminal knows to execute vim upon opening
$textEditor = kitty --class ranger -e nvim 

# Application Launcher
$menu = wofi --conf ~/.config/wofi/config/config --style ~/.config/wofi/src/mocha/style.css --show drun

