#######################################################################################
# MAIN HYPRLAND CONFIGURATION
# Modularized Config
#######################################################################################

# ----------------------------------------------------- 
# Sourcing Modules
# ----------------------------------------------------- 

# 1. Variables and Hardware
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/input.conf

# 2. Visuals and Layouts
source = ~/.config/hypr/conf/looks.conf
source = ~/.config/hypr/conf/layouts.conf

# 3. Rules and Actions
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/autostart.conf